/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: ABOD.ANIMATION (https://sketchfab.com/body3d2005)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-c2e4294c32ea4d8b850e152fc26aeeb4
Title: earth
*/

import React, { useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF, Stars } from '@react-three/drei';
import * as THREE from 'three';

function GiantEarth(props) {
  const earthRef = useRef();
  const { nodes, materials } = useGLTF('/earth.glb');
  
  // Rotation animation
  useFrame(() => {
    earthRef.current.rotation.y += 0.002;
  });

  return (
    <group {...props} dispose={null}>
      {/* Giant scale - adjust the values here to make it bigger */}
      <group ref={earthRef} scale={[15, 15, 15]}> {/* 15x size */}
        <group scale={0.01}>
          <mesh 
            geometry={nodes.Sphere_Material001_0.geometry} 
            material={materials['Material.001']} 
            rotation={[-Math.PI / 2, 0, -0.262]} 
            scale={100} 
          />
        </group>
      </group>
    </group>
  );
}

// Preload the model (important for performance)
useGLTF.preload('/earth.glb');

export default function EarthScene() {
  return (
    <div style={{ width: '100vw', height: '100vh' }}>
      <Canvas
        camera={{ position: [0, 0, 50], fov: 45 }} // Camera further back
        gl={{ antialias: true }}
      >
        {/* Lighting */}
        <ambientLight intensity={0.5} />
        <pointLight position={[100, 100, 100]} intensity={1.5} />
        <pointLight position={[-100, -100, -100]} intensity={0.5} />
        
        {/* Stars background */}
        <Stars radius={300} depth={60} count={10000} factor={7} saturation={0} fade />
        
        {/* Scene elements */}
        <Suspense fallback={null}>
          <GiantEarth position={[0, 0, 0]} />
          <OrbitControls 
            enableZoom={true}
            minDistance={30}  // Prevent camera from going too close
            maxDistance={100} // Prevent camera from going too far
          />
          <Environment preset="city" />
        </Suspense>
      </Canvas>
    </div>
  );
}